name: Build and deploy

on: [push]

env:
  IMAGE: "docker.pkg.github.com/${{ github.repository }}/dagpenger-features:latest"
jobs:
  build:
    name: Build tests, package tests in docker image and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java 13
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Cache gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build --info
      - name: Build and Publish Docker image
#        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build -t $IMAGE .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push $IMAGE

  kustomize: 
    name: Create and upload testsjob yaml using kustomize.
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Setup kustomize
        uses: gtcno/setup-kustomize@master
      - name: Checkout code
        uses: actions/checkout@v2
      - name: kustomize build
        run: kustomize build kustomize/tests/app -o testjob.yml
      - name: Upload testjob.yaml
        uses: actions/upload-artifact@v1
        with:
          name: testjob.yml
          path: testjob.yml
  deploy: 
    name: Run test job
    needs: kustomize
    runs-on: ubuntu-latest
    steps: 
      - name: download testjob.yml
        uses: actions/download-artifact@v1
        with:
          name: testjob.yml
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: testjob.yml
          WAIT: true

 

