name: Build and deploy

on: [push]

env:
  IMAGE: "docker.pkg.github.com/${{ github.repository }}/dagpenger-features:latest"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java 13
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Cache gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build --info
      - name: Build and Publish Docker image
#        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build -t $IMAGE .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push $IMAGE
      - name: 'Setup kustomize'
        uses: gtc/setup-kustomize@master

  kustomize: 
    name: Kustomize
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Setup kustomize
        uses: gtcno/setup-kustomize@master
      - name: Checkout code
        uses: actions/checkout@v2
      - name: kustomize build
        run: kustomize build  kustomize/tests/app -o testjob.yml


